"""PyContourlet -- Python 3 port of the MATLAB Contourlet Toolbox.

Public API mirrors the original MATLAB function names from Minh Do and
Duncan Po's Contourlet Toolbox (v2.0, November 2003):

    https://minhdo.ece.illinois.edu/software/contourlet_toolbox.tar

Short summary of the public API:

- pdfbdec / pdfbrec   -- top-level pyramidal directional filter bank
- pdfb2vec / vec2pdfb -- coefficient (de)serialization for denoising / NLA
- pdfb_nest           -- noise std-dev estimation in PDFB domain
- pdfb_tr             -- truncate to N most significant coefficients
- showpdfb            -- display helper
- pfilters / dfilters / ldfilter -- generate analysis filter pairs
- snr                 -- SNR in dB; alias SNR provided for MATLAB compat
"""

from .PyContourlet import (  # noqa: F401
    SNR,
    backsamp,
    computescale,
    dfbdec,
    dfbdec_l,
    dfbimage,
    dfbrec,
    dfbrec_l,
    dfilters,
    dmaxflat,
    dup,
    efilter2,
    extend2,
    fbdec,
    fbdec_l,
    fbrec,
    fbrec_l,
    ffilters,
    getPerIndices,
    ld2quin,
    ldfilter,
    lpdec,
    lprec,
    mctrans,
    modulate2,
    pdfb2vec,
    pdfb_nest,
    pdfb_tr,
    pdfbdec,
    pdfbrec,
    pdown,
    pfilters,
    ppdec,
    pprec,
    pup,
    qdown,
    qpdec,
    qprec,
    qup,
    qupz,
    rebacksamp,
    resamp,
    resampc,
    resampz,
    reverse2,
    rowfiltering,
    sefilter2,
    showpdfb,
    smothborder,
    smthborder,
    snr,
    vec2pdfb,
    wfb2dec,
    wfb2rec,
)

__version__ = "0.2.1"

__all__ = [
    "SNR",
    "backsamp",
    "computescale",
    "dfbdec",
    "dfbdec_l",
    "dfbimage",
    "dfbrec",
    "dfbrec_l",
    "dfilters",
    "dmaxflat",
    "dup",
    "efilter2",
    "extend2",
    "fbdec",
    "fbdec_l",
    "fbrec",
    "fbrec_l",
    "ffilters",
    "getPerIndices",
    "ld2quin",
    "ldfilter",
    "lpdec",
    "lprec",
    "mctrans",
    "modulate2",
    "pdfb2vec",
    "pdfb_nest",
    "pdfb_tr",
    "pdfbdec",
    "pdfbrec",
    "pdown",
    "pfilters",
    "ppdec",
    "pprec",
    "pup",
    "qdown",
    "qpdec",
    "qprec",
    "qup",
    "qupz",
    "rebacksamp",
    "resamp",
    "resampc",
    "resampz",
    "reverse2",
    "rowfiltering",
    "sefilter2",
    "showpdfb",
    "smothborder",
    "smthborder",
    "snr",
    "vec2pdfb",
    "wfb2dec",
    "wfb2rec",
]
